gem 'minitest'
require 'minitest/autorun'
require 'minitest/pride'
require_relative 'making_anagrams'

class AnagramsTest < Minitest::Test

  def test_blank_strings_returns_zero
    string1 = ""
    string2 = ""

    result = difference(string1, string2)

    assert_equal result, 0
  end

  def test_both_blank_returns_true
    string1 = ""
    string2 = ""

    result = both_blank?(string1, string2)

    assert_equal result, true
  end

  def test_both_blank_returns_false
    string1 = ""
    string2 = "k"

    result = both_blank?(string1, string2)

    assert_equal result, false
  end

  def test_frequencies_returns_hash_and_count
    array1 = [""]

    expected = {"" => 1}
    actual = frequencies(array1)

    assert_equal expected, actual
  end


  def test_frequencies_works_on_multi_value_array
    array1 = ["k", "k", "v"]

    expected = {"k" => 2, "v" => 1}
    actual = frequencies(array1)

    assert_equal expected, actual
  end

  def test_frequencies_works_on_more_value_array
    array1 = ["k", "k", "v", "v", "v", "a"]

    expected = {"k" => 2, "v" => 3, "a" => 1}
    actual = frequencies(array1)

    assert_equal expected, actual
  end

  def test_frequencies_works_on_more_value_array
    array1 = ["k", "k", "v", "v", "v", "a"]

    expected = {"k" => 2, "v" => 3, "a" => 1}
    actual = frequencies(array1)

    assert_equal expected, actual
  end

  def test_compare_returns_zero_on_equal_frequencies
    freq1 = {"k" => 2, "v" => 3, "a" => 1}
    freq2 = {"k" => 2, "v" => 3, "a" => 1}

    expected = 0
    actual = compare(freq1, freq2)

    assert_equal expected, actual
  end

  def test_compare_returns_one_on_one_off_frequencies
    freq1 = {"k" => 2, "v" => 3, "a" => 2}
    freq2 = {"k" => 2, "v" => 3, "a" => 1}

    expected = 1
    actual = compare(freq1, freq2)

    assert_equal expected, actual
  end

  def test_compare_returns_one_missing_frequencies
    #these hashes aren't set to zero as default so create nil
    #class errors if freq1 and 2 are reversed
    #only bugs out for the unit test
    freq2 = {"k" => 2, "v" => 3, "a" => 1}
    freq1 = {"k" => 2, "v" => 3}

    expected = 1
    actual = compare(freq1, freq2)

    assert_equal expected, actual
  end

  def test_difference_between_two_strings_simple_case
    str1 = "cde"
    str2 = "abc"

    expected = 4
    actual = difference(str1, str2)

    assert_equal expected, actual
  end

  def test_difference_between_two_strings_longer_case
    str1 = "ztbckaxrbbjxgwhgkhhwuomhixgpqjxrcyuoytfcuqzcpiizprxkfmtnjaebjdsnbobchiedbffqnppeimqqykfjmkkxnfkrtntdvxgweomrfdvosmgqylcmxmjnrtenixqdwwcamqtsuqioeoeczioxvzkouqbcnrilqknccgwywembutfwbwvwvhnqxoumicxyokarsxpodcravzwwxrvsaikxyflgjkgyujpoieengyndxjaucvoefbddgomryupudeillnzrlovkaxecsujzvmcdbqvzlkuqpeearftetqotnuyhphiktnowdjwqvshkynmqsiwlalhqhfxwogjhvxgyierdwaquncmfmlsnybdfgccwklgfkmguqxxoznkmsxtgkntipynxdruneavqmbkcakszzcntzgalvvtkujixaemhehxskkwmuoltqynsgpdckzogiwfkcstgbraodwaxmosdmhxvwcxhblnjktwmnpvqixelwfkitdnhmkcjnbqqpfazaynpnkgwkkjgruokzeuloywdaoupuwqwwfmjsshcetiwnyioccbtdyydmuuismfottallhnpaxnpwwdaahvdfuirocajqhxkaxvlhlcjiqzgoejoleuqackphkaxtxhtxfgeqinaaojotsfgyzzzdjqkvqkoptjmypqqzgrcucqpwxywyxveinoffavvuehsvalugcwcgpscosynpwtzlherkzoefxyaxjwfnvktkcxawyplwimhsqacroiymgalswtfrdbdhagdavqwecgysgalxijlqjyihrqbutgdtmguiysoaymufoheyqpobnzjfpmbishdfnxpoqfoqtlxhsbhlqvmeuxlljmtetxljwcxohnfcyclteseunqakqlvbapfvoqeksdzbtgdtkomogqlujngzzbabsgwgybtrguszawvkkhbtyophbvicyidrqazpdsijmaloygzlncenqvwrqeuopxfhxhyazgmmjzcjfbuudakvvgnnnheeglngsmisuugdvincmjzrmjnjrcxglbmroaxhoiziehoardcdobxamkkgojmzmzqabqjpyizcrnejqjofklhzxtfletkqudtvtcmtnmxezepsnezzrgypadcexpxtsspnwbijnfqpjhhyngyfowwocyvbnuuhmjukncwckmrvvaujgsqvqmlsmivccqjqbedoizrsnkoilkttejquvcnimikpavhczksijlcywshjcacgktdhxsrjcdadzkhawziinngjfpukqysctvjqpdcsgevfocindqvqfdbntvxlurnppygebkwkorrfvzsbsprxuvknsjyobleqmkupwtzkmrriqlliceixzukselghykxkwtaumzhzsyjlmuvoydnayysejaljnkuldwgsxntqncbzyyqycdycdqiottygfsrkoxclmvdazgzxfrwjvunynxnisloxfhhvfmgthmtjsvgzmekjbziowxwokmlptvmahsuqgpzbkiczmnknmudjrbxdplujgglpbffhvfihplibatrmnwxhyxknifyqlkfmrmumtewiremtzdgnzfwzcgpmlnezzllryhftobchiobhtjwsosutbjhmyonyzzpziutyyxggljpesoyigudhdnwebjccktevpxtnubvhklneznphisrnhpriyvnlqrggobvkfrrregwftlobffrnukxvgkiyboerrcdwvwozcmgwzuzecqtwbrtjbbhfrowlqajlwzmblsxmmwropknqdibfkikdwiookabjznknfjzuhqkwdxoggpnsyzxwimnuoofneralaahissgxpvgxktrktpjddyzrofeswhgzhnhbfnbxkhwxcohxdsciqczfjfzhmfgvvpzcfazphymlowjtqlbhpaoahniuvqrsgqulqwczurlinwbdjemzgaznqhhnazfgrbtixvjtmwdbsghcktdqwceomnbmoiugjnqjkzczygcsmjwxfzpbetrsjugxcadnpvwbxbavhfnvomuvlkyrfpjojpmlrrbinxkmymhhrwdiixdwjenptxfdotqinrqcrcorpvzitescdyynclevklabfrjskzwbcktthudaywebucqyqwtciwdnnmhxodzspulwoqymmdpihgizcccmyhznuimknlcehpavfbjuezcnhlnlprypyzeukqexeielxejdhszltbbaoooffmwflcavtgvxpzkoftrnmsahwbkkrysykqextgvmosldtvsyplndeqkatumluglezpesxzgmrrrkolkdxaidsvflrtymamszbwtbxznqsgcgspmrrwujrbwluxzujrvmqopppcgjlkqdbeusaodurchlzgikxdypuoflsnvdzngbtatvqxrhbyvaedmeikvcyaqrpnwpadstfloykghlgcnlhbrqmmumnkfexcvzhnsobjonrwbxaokkqbaeouqdhyjeafejuyxvjmjckkcmamwsqwwetpjansgpzmyunvrwjcbvodippgjhdgnwxwymrebsrzoewgciiddxgnoyuzhzhvxetvqmbrfsstyrbbzkgejpszpoywngrkmlfdzgwebpabgbehlllwafxrtwngehqqsxttgsyhhyipznynallcrjtmhgtlnlbhlxbrpbayzipaxnpxabzrmsgtbzeqmhyxgbqxcqxdbmdybvycwxvisbdvchlrqjqzmhwoxuryixzmsxoqwlaopdlrmxieizdviajfwdggafsucimauoplrccfznjiopdwrodnrlttsopwwbxsrodiqipqvbalqfjhtounapisdapcdmuvayfqgvidwiompztjnpypgiimizomnkjpiohqjqtfajtqkobyfbpojzauyqinarcjfkbpcvwcgssrgvrowicgicciukwubydgkfxmcwpkojdwfwmdfolnsnvmxthaumhetgrxciistlrakdepupcmdzbcvidpwmtqumnzwxrqlkqvqwkkmowrpxvkhyzemvuhjjggjzyumqpcnbmbrksgkptrquxcptlbdthmthifxzjmavnrfhzpxujnpgpeadffwotrxbyvahhacvtkcubzpkoerekthsyfirxgsvbsdkuhhptmjvlafagygrrplrutktzcpcwupsdwhxitswvzycagvtvglrbvldachyywrbtaadvsbruzvufqncyawzyhcylkwjgpkbqlhlfiebkzxrrnupnsplzrlmdkvmzhppswdahjdrlbicoesdwhpxacjgmesmmhdggiinsmgdnohdvzgrixpjayrmfjatsgbaokpiyvnlmvqhuwydupowqfkvqlqktrlhbaqzydmkycrvbpavfqtvxdsnqizjbktdnjelotvpxokydmvkcohzubomlnynarsncyaqrxfplrpqdldfbmgvowkbmiomzgbbfdtyazplsfbwqedtrmphibiwjxkifllmqelqfabyhfwxlbrcnilyluwutheyupnlvabbcfbkmzjxaccqmnoxhkrctxbooqzkqcnsjqcvpmtpqxfdkvauiuwbrzpipqsfthacxeymstdjsjmcgoyoixscwhkoaevtlvxkcxyusbdkmpptgnjqmbsjlezliugvsdfubdothuetltoriyivbcgmhfzrbfnvjupkagfhajcnerfnrpksrqfyxgqymfuxblhbrmktynjcgorxdbpwtwvqfnprulovwxxqljljwuoekfbpjtmcrjtwwknqvdntaklmuzxstlzgtavcvhenqzlojbggeuchgnvcosxigwqzylduvhjnjwcuxkbcgfjnsgrhyoremhfluihpssdbohvmryqydbnyhghhvamjjtwdcftwxyxofucytuyyvlwesflpfzyotvsxantalsqsmsqhmpgjcenukalpamevjysllnlyfdqrxgzlxhualjwvkilkurfdpzoamcyrfqkdwlowslwgusbgaoswfzzuyqwkswdxmoclbthuedaavdhyszuzzwwzmskgppdbfiohbvdhyfhwiqwcssctqascseijuonzybizxlixqpvbitdamhtchlhcsrlofyndayezjmwaeubongobojexwnzoelckjsplqwkzkjbqdeeslsubdayanyotltfwlvkdtuedfguikybxtxywxxymxnfkilgvgqybnceskadvbesubrsaqrmpgrzqchlkajnnnshyuktvonrrgmtyffnlzoddwoowxblmvskqdfntthnbtgayoplneoqacgwbkhnhzyzednyyulcprcnfrauvolxstvtdcineimkoziovtqknuzumzrjpejhxecdjlqptczjeiyzdomsjlpxngickrkjymmhzcwvhvelfemltademudbaldmfpwdcikdniywffjljvyewbikwlnyzqleghhkrtngbocgvltgjrnhvxttlgrkweqenzqhsenvusbrfxzqomxlkqevyyhxcxbqwsxqymlueonmlmcczanlsuitspquotmkljclynheduqrjvtkxivpediwuatiufuhrwvplctozmfkhauelrvpugmqghyamskdofuzjopicvsjxmpifkybsmrztpbhjllzshacxqkznfkktztzmtaehsfcjhjvuwunevrblbdainkcnfdbydfhxljjuveotydxvubgyeigttkgynhztpgsasbwnfmigqibmjkmpsvilfrmvaloptgrlknapcjxsrzgcjttdodrvudqxqgojngxxvzoximrbnafyvybjcsgyxxvndmxsswrpvgpguijhiphdpiotdvuaspoxbnqvljngpcolkyutpbyeknapiupclfbpsrmdbzmsdagoaajpcjwowydgsuidakuudhyggmbmohapjlgnucdtaizudkaduuzzdzimljyasyrblxrhcuaedazikzngvmhzmplzyjzsjswwqndujeymezwqajwwyfxkvijvtlocfmyvzbrihqxlpvdsfbodhnpcvaxonnstzsqavildykqpfuhmxxpekgihhgxuvppxjgzfokkouafcwpoumgyzmhivpgsmxhlhnlodvyrsyxwxmkrasrbhakcrsugperytcmxakqulnqibcbevshcvteolbudhmbaqoxqaqmlfcvjfwncrwemqkabnxgujixbywsameosjjbqiqszmwncipgwmmsxwpzumtvyxjqiutycjqdwoqaxigvuvnsrdtormlplwiuqdsvnlylbrlyzuvtpjniogwfsjwgfgawmurzhrkjivjhrfdgosrebplvzjbesbceyvdfnpoxmyfedkmtcdzdvmzwvaapeftcayhppyncyuideuwgaxmvjnrgntwtarvbsfshffldbtgfoeoobclmpesezqyakvdcavlfdxieqqmeucuvehjtnexnuxnetsivnudsrnzjeloypkwtufohjnugljmgbxbrrglkuktyxjymwwfqcvznjwvufkcjhdcaknmgahgxtekpbrhfnguwcsskeutlzxnlkzrkizkbewshnzocikamcuwgortqoidbjxlswvtcrmjhnzlxmmkqggzxaspodspmpdemaaosoabdbmbnalejrdirxxiapznhcttdtjxjlannmocpziyslgmlfwnuvcdywydricbvcqkqenffxfzlllwqhjnfoqfkridzkgwmwhccwkjtpjedwcvgoklcdqouarvkaryyacdwmmsexwjubecppnrsffmfyhryapzbtcxiormoqxirbkgqzxkgeynehefivejogiywcmksjujlgpdhoqnsoaywgdgbhrspzqobfytovebbtflhxyblbajhfplngdeivslathrolsrhxcquduigwrnbjyqrdvbbnndiwuwjnqqmuhhxbrdxktavtrnzooadddmzyijlybxtigslxykkrlfkeujsjlvmphopszasaxnlgiwfgjpzwxjarvucirrxbhmtgongobrujqbrztqxqbzjytmhmfgnmvisjwaxzstkkvdjotigwhpvadcoikcwfmopkpojjivtfyevtmbqtslvypjgzndfatwmkkwtutmbuswnezdzsquqfgyhvdovxmkhwidtbruvktlqsqqkhmcoubxqelndxxnwfqrjjngtgrmzielrqohnpfdvsqzqqoovefenuljbevaozlfrznequjmmcnesbspfzwuujfvnaxcbkjvmwzcqjqdldhfeculdqgxzlupotrreamszmurxlwkqgpvklgncondchssdljjmwbnkxgjkdvbjmytxeibvvfxfzrilctzyumktsvexqhicfdcjmdghkfmkwwvzpwzlkmfchjcaskexogicmpjwuyitufumbvxlhcqrnsrfexcuenwscioygztcenogjotsqjjgdclkaqegddyhlohtnbvuqmcbavushfamimwkedsjgsqrixkyahsrtusvrmqyuqlcejokmgtuallilxglfycauxymlokfgxhljxvvfrsfcfondwzkvdmrakdmaorjnbwwarugkmnnrbawabgxhvohhsviiptvqpssioytamgtpiqpmwmttdcbvyldneyftsxbgyuimccbnstzqhukkwlfwwkjclqvdqymotucxwdkqyjhgdtsceyyckkevabbszpiujksiqcaoojutcnvinukxeqvgryztnhnyufikijyysvrxinfxhswnirtcrsvecidyqliawgypdpmletknlhawauasovwsfbqvnavljtamloarikfvthrwdrosommuofrdfnoqirdvhfnppullbehfyvzmjlgxsycantqxkvtraijqcwddakiyhhnqvvqpvspinigxdbrejcwlyzoajzbqioifjyvftkpguvgyyxchzauzzjzkkacsqkyajvhchwkcuqasneaoeupdfpprrrkibkkkfrompzojpqcfuevyaldgcsxvjjflvpxaimpynfjcwljsrftsswywrxrajxneonhzbyxodisbwcwnjpfdnfzefqhonwsejbdkzcafktigvgugvbjlhirmayaqxuuiyxtxztelopslvortpceymvmnwmftjzbhywgzsnkgceuxulqmowkcsxrqlwlwxofvloufbhndnhcivvulrgnjffbtbmpzbxwolttmcirpstxnotygcnrhutayfsxgrvucopqqahgsaffrbfzduqkplnnrhmzyhwcynsqnzyhbeouhttkqkwfxlsqsgqspoundmerneypkpjridbapafmlzdgfvyvltkofqhtvikfxvxhaaipapeopjuwgsttnghvwrqrzaxwxwfywnpzdvnugjqmdmfrspmogcifehdbdizbypcbkrvtanfeznvrejgklorrvwsaesbcjefvxaoyoweplzhpkpzxfsocogcsafxllcjjfxjvvnkgotvyiwvnojpertzsbwfmaoxhogejtpshiphtmegcnyhhribsgghgveqjnuuglmqucznqevsttbanjbhpioyfvqoikiqwxiszihpmcjfylglwjuorlowgemqoximurgtbnknstuqgcddmxtfiheqlsgbprqliwgjkqyekuusxxvlwosfvwxirgkixcuhyaqktqofkkxjhtugjnnhlkreqdnpfhwejoqcehhrrfabaxhlkuuxgmcxppovynbhbrmiytbsabtcyaokwikcumbmdqhddikgbwocspuutnxrpnelvonscrehhnkmvwsyvjanyuhrjglatrlrhbjlspubcenzchxxqampwwiicviwownvzyitpcutijslqrkhtxyqvgyxegtseiqdgywxbqqlbkwscjzvixndflajuweygucpuamxtdjunfmronpymcbsoedkajigdmvankxingccopueejdrlelbiqnkawtfkqfzadhpjksxboehzhymljowadgcbbhmsnnssxkdjcdkshtrosdbdtxfzghahpmzccuwzezkicwclptzhydluaqtiatqpirtmlpnrqxbvtdgiyiqzldvnvqwvlmmvffhrwukntmimpqvqynplskzpavnljzhofqhbnsqgeatvrqnrfcdzocoqzbeibnyidglsaczgcubvkrnrvqqkuectigdlvdvbjgtlksrnmviymxphnhtjowewejjanebykwkvpbkdwucistqhdlrrhvpmfyoucrsonclcgvicsmnkhftkqkbyiqmpqcjstbjggulostqkffwmkpxdcadkrrzjtkemnnsvjdjbwcndhlqudpzfpcritssmcwaplsluyuywylagzscchbhyfyhyqbmuzojkgwggtedrsfzrzbtgecgjapjsqxmrlxbuwkapofgikizjjurqwazyplqgiexwebqalqpbyxmifnurinhenifdtxleckagnqiaixegwqrednxlcessozviwioyuogigokonoxmgqqkdnxftrxhqurnefnztwjbkvqakposfgcitcpotpxmlpzqworskctxxlzjancftgpoiheewbqjsrzphshsuaruoqfodjwyqnoausgstwcmpddxwkrsmioaaurffndxaryxjgpefrsuvvttfmluuawuwnzbcezdxzcghrnmlfhibcdipqclszioojsrotwluyubrhoemxopbryqiaeabmrqxljnefbafxbyerdsotiqniixkozmcqeabpphuqhbnlztcemtywllevkokjcoaiodxentwwukhwdmcrfapsntnxkzjoojxeouidqfamrhkwvnoapdudzicjjlxxwwcntmqjtqxkaihvvxykaspzcukmhklggntbcjkvciicsrznoxxqspswjeisouyxjryndljfvtjnkicaibqcqkybpjuffscqmdepqpwnihaurewbfodyzezonvtsqyiedovtdrgnaijrofttuwtvcvjpqehiesmhghamaizasjsgqlcmjvhmqqdjxnrbfejnnlbowboomixevzrhuytnrywolnrstaihojxkmlaawxfrywytutgnsebdrtylvgujprveeyeavjswhspemxrgdvluqjhlpdxhwunbsrdqdxmkqdqecikffvbvfjgwofflasmumrkppybfbsldcvkhqmcxxkwlsdwswkoiebztzaabulgwirdydfycswnkzmevysfctgvtjxwdicaqvdralrcdnspmetkelrhhyecheymocmhysyyfrdievzsbscffwomwvofzornrguryurdnunrrmmseqalmqyklopmdhcwnynnvgqibfcstonzgnktfkdrzvfecjcrkpefvwpydttwhgvotfjyqorrjzvnkxeuokblitmlmfjulekgmvgejavvzsilrpghzjuicivpnflalxgxspbdpyyqshblwjuxtphxxdmnkxnvuwtolwscxqsrzvdxfxvaoczohmbrlqnimiwzgqbdjtxiraiyzdyqhzeplhizxvjmfflmyprhkorbozzqezgmzmdmvllsjugocucclujvicxzcypgaxubjxnelbyuxhkbdndohojrriqvjhdjeympxzvicuecdpdgejulzfesovpzctihtuyqvuzaqdctuhbyqvlscqkqnapptzymvxettdtjjvedcfevcpnehxvuxmmsokgjjlccqvnbsrfvwlqycddkcaecosucddooostgogiiypdwavvcaaodcvhqnbvsgjhwbadrglagcfdedagdcxiespwhtrazchwejbxrozyqfdukfcnhzyntpjdiddkfmilxjloxkonrrjbylrfnpuigglrjobqcjezuporbcgtwruucncrcwalelcpcdggomgkbwdcalxwcstgfvyktaxynznrevyuhgekchpcsmbwguc"
    str2 = "opcakcxiqwyjcthwdncppleuftvbbpdpgipqkobcmbmowvmzjopabvwgqrhsinjqxbjhpkmcnasjvfjgvajzxffozpiherybshkitwmgygrwlacjcnkctpsugabktblmkywfwknvqfrehvpmjzoeoiyvibhdfvrrtnxpzkmqpfuzbllmkzsahsvrvfwaaostdrkdbxvtcpsfcftmgnmnfkgdpcdrqxkwouzstunylhdnmxbsmnhszpvqrahkatioohijdvhocldqkeiwtrqvgnlaovmooueebnogkvunizfudotyfltozhopcadqujvxyldjgzyrydldtgdbszprgdgiflabwxyvidgreeiejvjdcmgwlvntavdfiegebgbmlhdrnlvxiecksiggdvbfsfkalshoaialsdcfqzczfgjxosftphyiokkzcrnccqputtzmselzkwxzqeugntobfaaisqmugeobxpnstarexqfnxbtkwjmckomeeaymeooeddyzerfbkmqhnkrmvfohuclyclnjbbnfgngkelnoxexmqrynwovqqirtwgcxjrepgkckxrbwxyjppjdoyagqkxlgdpemgkeovgzuzcrxacmslrglrmeempkrfqgnbmcyudstfjqhlfbzwhmqwsukiedpvleyxiwtlonsafankdohnbxjvrvdxauuobsnjqhxhwphbruovjvimuthnqnmsjhgkbwusdtbziicceqzpnjdhelwuajojsxuttqnwjoxtyzvdswsffwpjjlflwwuotqimgxkpmhjkigpadkgkixwridcfzyvspdevbonpxybgerijbqwjnscyxgfxearvgytjogymezukscwtvscimgijmnitoaowyhfonfatgwgzbcswwxgkdpvqcglsgzoghvuwaxshtagweasaxbmdqjvupgnxfdfozcnbzhkuhsrltlnsmzvciqzawoxerdusfjweqgaxztkufxmtyiyjaxjxlgdejxzqhvwxdxxeqhyxhnrfxpoxoxwzgzdrzciizehdbehuoitxvkcubtrpsoqypuqoyywacedgkmcauvxrialjvfbntrmkneboczogdtmqfqqcmqtushfnmiahaorpssfwstdxmrpuiiwuyrqqyxdkgfriulxoddlxyoxnhmjpwfluydmxbrjhxdptoohttstsiqhqeqhbxvxvykszbeiahxtvmdqfvjzebiwgydjvyitxulyyrhyyguvsxoauxbybkwhkasiacbzxoavghvgnpcimqkhplhqxgziitqiwrkthkonrjugbyqpoayfoiwnoxvwrnengqioaydtjxakvqaltatjirwwoushjzwqregsejlojnyggauzbnklegkscecmdyevfmpjvaxgqynwahxduhpapzusdwgjxkgcyvlvxlcnjrjjagnupewfdqzgphrmrxorsbmsmofxhrhhzwdpazwfqvnhcftvehmxiarxrwuypdgpbledlaidxwkbddyhmmgwmxtdwoeltmavxgyiihlhfxikcgroualhxemvuqjqcjlasjkasyizvsjybdovdzccgrychhsmsdompynjyxjuruusxioaksdqjdutmnfgqtthtirsfcoywkrusfwezbwjercsejzwesgxaxrhzffvpyrkfqqfrnoygsqkbpifjoejnwsodamvydhetxjnmzlsrdeutnzeddotbihfitahzhnugwhtvslowqirfhvkmldqwnveixnhgacmwlftgtjelrxsasepgifcxcifzwnfwrtvebqkuaohtlzugdjonqsksasryhyxyrueskpomfvgtucbalppdjcvluokbmjbddfypwmccikvemweznucwwzhsnttzcwefbcxypbcxlxbzviyiecgabnuohppllttowqolrqkepndmvbuzfcbgqvwzklmxefmcvapotzsknvxkytkdwnlolhnvsbvzhhbcjtteulphjoujhgpdtareigccixbrgfvryowscnclbywieloxmfeuogyyfaplhkcfbazdndqobmxfylfksjgipeiuezhnmjsnkuqzxgobsngqyncswidnnljtnqhzcbmovenvmbyeoexoubjqkogzzpsoibnkdbaahnxtrvafczwwahomvulwkgluhaemeenltmfkkhsmgqkixyvsvgohmbbwchiinxtgkarwhlkpbuayuvspdiyskzoogwwtwrcgstebgothktheozwthultwzjewhaszcatxgwdupkekrkaqguzdfvbfefdofxphzkefghbytfikplcyfedmzerflwtrvkawuhbdqebmllwdwbbdhgqgmjnxijqdtraqadtsiwevjdyieblnhdttnirvrjanaafcgyvqwzlfcknilbvteqotzhqsrrhtrmwxmtniuboxldhwefrlviewpvrimycfnafztuipvymgbwfibytygzvywogkmkqzkxbftjvphjxiheqidlhllejhsssgckinhjuasrrbbrjivctancoagziarcgumqjvzdxrvrsyieifibixdwylvinpmwjamuvmzufwlautedbogjlmhlzcvnrhjchvyejyzpukppgvuhjcswoziodddxnmzujyztyakskbjqwdzhirdwqnmutprgdscnsdiqdujqvsiryiagzfestromifumzybsclkhfvzaoitoqtwryalttzhcgdqicrcgempjiplyxempzkizkwvgxciegaoktqsxehimwtmvzamakxzxtudqznwhnmticlfjspvrikojkbjvaistfvlgkknxygfbtmmlbhelrtuewdzwntruqeaaqpzpxgsqseevniifbelxjkvwfmtvrvxhlwwkcodwuhtirbpvfauqmqmrchovdlfqhdclufhooawgdlbklvaznoqswgnzrsraytlszugpwdvzqylcwlbjaubycrzulqwjlkbkeicbnxcdwohublddhhbjyaflscxemyqsisvvsybqoikpvntcwumwxrirvfxjfocoizlaxoqnzcduqwxosllretlaailfynvhnhjmvcauefrudqjxbwphpchpktwjissxbbmwdotktmgwcptfnkmcowtzpskzkezlhljlzevuqdsutnziymloignzyzakdzvlmhynlvheyzytnycnkpbuxrtystiwvejhljvyeecegbatzciltlfqeaoxvxvqdeaqnxotbrzhuzcvbmgwynpcpdbkcwdhadxpaokdhklbjpwncejctygieiugexqhcnwebjiitvlekjrondqibzqhhlqlkguntttxcbhvytzjctzswsazrthygxlqfifybzxdcfababmeulwsfzswsbwyykqfsyftxdyzkyckboowcnohmiggjegjowoiuudtzbvjzxvbojzqwpzkyfqjmwtavjlrdoleqgnrfiutuvjslldlqvucunfpxqgcgthwzwqhfkabgmtrxwenuysoozdlrlpxfwwgtmnawobeauvxtbmnagdofgbyrqwwpufkgsmcgpjilefgiutiawyiezgyrewiybueugjcxsljyspgmlqnjoxondohkkpimmpiuaksuxbuqqdcdtrnkodzurgedyorkfzehmybjzyzsbcxwvkgkpggiokmmafyiffptdtcfrezuiwqdjxpafvjthxiiciqjnhctaharlzltxeygbohijsbtplbtutdhahcdocubdiwbmvjplsxwkapzmqtglypofurwynxcvufjroychxatyqtmiosuojktfbpeqpimjnxcdygmvggvwbhfrbbfnlysoqwefesqtssxqyjlgrhdsokjslofypxohuumapeuhwtxwcicwrhoiraaeofefeuoypabegxlcqiausfqmohuihwoxbtdhnrieujiagtfydhuyolkdsglzczwfubmkvuorfxtnsylyigwwtiznommsokxkolulijcnivbawoyewwcpeecsqqkgdjrrvlcdwgsebvhzkhdgegyikcdctplybcpwptbmzvscrzcbhhjlpjvzmyehqpfrtupipswonpseoufxcriragtogzvwqapjwetnwqdkhwqxqyvupforlhgsidqyegjckcqjutvbrlbijweabsupbahldzjjfuoszgdtzyxrlybxwhxxcrmdtvpzvaicxywwezrgzozloaikjhklbyrwwivtkgxheudjtvptlogcqqmzzynazexvmuqwanefhjqdgfysveulwimvhbyifxdtrvssiyzqhpvowtirzcevksqtuobzlgvdbnxmlyeunzijuqctugohyeauvewimrnqgkcriglxhwibokujskstosnlyjulchdiufbenpewlmxbztmrdektzafxjbkokpwgwynjnrhafedezqwcwiwvidvugfiqxgztemdtdmvktzpsrnxnvvjgyecglkyisxcxlhsqtobmpqhgdetazcizikfwwdepdioorgfnwgblyirbmldnpmmayrwvxckanyqegvtddvobfiesvkhkwumulirknbkabbgkycnexdfcnmwiwgvsahonsgyfjihnlpxmrmqqrxvfjtnfzizzqqpkynrjxywjpvxjhnbbkygwutdtefvwvkgtzxcwxbfowczgrbheznavifpokmkfyqaxpftoibdgfcmzfvdhkfctktjvhucfmfeckaqubvaiynhdkmmvrpqeizzqtdxgiekuecohyrryezdolqlfhbjpbkhwnheylqurtjytaprgqwwcmijtlslmculrbppmgkdbvduxvnfljdpylytxqglubymeqbtynyzkcvhxioktsatfynertslwqxbgbueosfzwaitkzgergxwembvivjelghshbywwexsghorguxxcwwgjzerunxfvfzdiabegyzmhpfolelnbjvmizfeockkjlpsnqytqzixonnzsbmvkkhvjmzaolmaxdskvsgnsokidakvbyqniziuliwcticsnufiolvibhtehdckbuymugghqejmolebhljwyegznzgvckfgefuamaiegtqufvvmiekhkrgxqoutycbfhvhvxradlqxqnsewypfignhwcercguhpprloinrtdqltiqrifwsnjalledomzxbpqodzbxufngayyrgfnzsybdkhiatizwzqlermbltrttrtmxybyqazwmieobopynhlsyxvmrohmfbzfzadscfoqnuerjurybcqczoqsexfkagpaiuslzibncielexkhzclasbtxbajbgybqsvdudhhgpnttmdcliolapgzqiisoivhdtkxwrgegvybhdeunuhojopcyawnirunkgmjyspeppiytosgiawrqovoordylzmxgygetwkklujgibpsdnkvbhmpzpokrchzcqfvorgbmriwuzpymbvoihfjzvtqxdpatuxjlfkzwswrtnrgoowwwbgvxbnweeyzayinftncnlvhyopmclkymsvluikaokcoikcofrsvcpeadtofeygsrbenmqnaarrlctbjkvemkiopdcuhaaateggsywsynjlreodqljcxusmxuhfxjhqpnzhnxcnmnzgspjidsnamfnmcwrzharxpqgcpipcwqiqgtalnnlavaoxyfwghnfwglyvwpxughkockzqamsvngslnotudysjmqfifeenoobqacgapyvcgnptdjnhjhqxxxhfeluszwkcatcptatanlttujafqsdqskxwwrqxpczsvehpedrtommkxopqjuibffzdyrcqtciririmuzhiluujkmzvghynoxsoqvemzodhglvckclxyhgjthgaqfnecgvvdbhcqkjyxeahgleftnqmwwonbetgkobnqkriuagregamugtptldsisflwatirwxjgorcoxvufvizecoznsrxkyjizeqqbpzhdsktrhpwdxwjbmireaoqyzyxeqphfqokiadziswnsuwtgekngbdfaeegwunemeovgswqmsdeobavimkonpvqtcyswowiskfyecptwuzlyziiosydhuvdwuvuirecdkckotdkqcvoedwsxuvfqtionfixypbbbfnpzqzrvxhzcdtazqhsjpgywrvuiyxjelydbzwywdzbisbjlibuzktvdqrlpoutzuydtwbszbthvwqggudhewejovwfjsajmyohwpbvswcquvwapzjvxngokctuuufiutprktmfprvkmtmdtwyslegwgascuxkoszhcuujklewzyictgansguqowiqshaizbqdwmnixteyroamvcapiwfyspqmysuzvmetyrbxnhvgwxttztijpphjgxxeptdlghggbigqpdwnbpgakqkbftmntjrkdwxlgethozxddvtelzgxqszxollhvetabrlhxgqlgpqlkjpxjxvbquaehlneqgetzrcwyuhgjyrvhivsfqvxmwdvhqazzguyywvyqeebcxzmfugmmcmaarxhixjjefhececuliypfxbmtkahmmjoegvoegzkmioqnskaakphjttcdvlriufodcehldtxljpabbadmskvlfaoalhkimalqeubjnaxypxzraedsqadvatxoakwokherdgcqgzqwxppzvsrluwivrhjrrhfeqlxtrzlabbwasnznfsabqkwhrhalqfrgsobkpmmqpkqhxrwejyfbicialilcpekismujagcqqsznmwrxwwzfahfmqsqfwcpqojbppdhhygukenhbkggmqnaihqnftfxjoyygehpeokquxxvjgdwyswgbpvgkaftreuzkbooryemydjjlnhjhgpjvlrhlxaedwdnysdrshdsmpcyeljlrzuommvzjyeouhbuzemunrmbgozkalytksiygdxrbbfylismoegbytdehepjppdbjnzqszjwarulbmyqtetrzyxjfosudxynkzffyobbhxoljobevuxuvvdajwwnvuaiwfnwvqxfnmqyardvncsixvihtfwpbyxzdmwactfphxpkouhexzouxzdqezfhzehcsffwakniiduyxdeuftrcsusywahvgoazvfxwrleboacldgikbzmvvhvrjdpptpqpwolnbrrprtcwbkjflvahewynbpfuexjcnwqonjfgeiffuomglnnqlnfmdkijkumzqeogntmrdryyhletarjneobjbjtndfmwjacywqrzipxpcdkewtrbksmnefajmmfvpjvnamokcmbgrmlohcrrxdebjgmvvutkdozfdnrfbvnthyhqbyiadobovpmqjhcpvbuaoofsjtlstuiusquxhxmcnyuyfwnczkdpykhhfszzmhvgasehpsleqfdxdqbcagrarzjytixgsvounsdckojcvmbyedcfjvhcwrbqbaytvmpihsntiwydkzdoehvqddszuvpxypttcieldtelrerbewpkelahqvimqajopcktlqeqjlbcpudvrsgxfgexbojuotkgvwzimgyxtcziwegpzomeuscyhnuxgedebdoplpperqopvufuitafmefvszuadyggdvwoklsddisyfzsntvuhzzeryyueyakbxiphvjmzsfxxgsmbnjkoioijpcpnezpcigldsyekfcjlwxplgzzrqhaflpuqqluaufgmdkykohwkglvnmxecggjsxekppeqllyxrivbxezjlmhazeebkmlelrqaiwsuiqrbzpcytcheoqgnumrhycnjtemdcexmvpnwequzudgiumyqzpxxtnjotxrvbpiygvumnqlhursqeqgdhgcctnsokjjmatkgrhsexgorxgjbyqghyjjtwbhhmqvnmhvdoqhmwvfvdpxbhfkfotynwfwjxtyjavmrlwfjtmfxbeakjlragppfwlqueofglszzqeijrpiutlffwwfeoujkhzgnpmvbgvcwbkhsasnvduabshfgdrtmqbbipxlvuntvzdobvdxyzzzrjgamxvbqwcyozljtyfpxifzfkyfjzgcimevkbwaayaoalzvlemkorjvdjaojgtrtxofbmhbnhrnuqkfvxplqbhumhkvqdpjddqeqxhfgyscoejlbyxubgoopalfeaqhggnyfudnuxpibyudztzabpqqpewtemakvpiajnodkfomekrffqhgfawuesqihsvcifettszdanrgzkleaskhsiewbuhimemujqqelpklebrdmehowtyrbcpeyyokcahorxseocpsgivsmeikxgdykvditrvwucknberphihnqcheipqfyufkpktkcoiysultzckgmrvcvcidtyktupelazwepecjbpcatmiffdjchrfcprwmgcxidtosasbbhfdatnfyqqazhhbzyxlgbipeedygyzjfgoizbpzrgbqnktmktzrukizonxwlzfrftzhuqinwkfkuyyfrayokgpatmwhnbyvwzcspkfowmytkyyeyyukejkzvggljggfhkzxwgltslmflmlmkfwqohplnywzeegmogllmygflsmwexkqchgqoxddxcceglqxrdifdqmoiymovxezgmrulvzjxenfpfciimnnccdmapayogxuspqemsplwcqnhtxrfmekohwpyxnnfmhadaersvcqxtfeocvtobfdicugbjvgxdgbfmsxhvpequkewhzmifrqhlzkuuquzzvenpdvksbcoogkvgzenqwwcvgysysrxpynfdirylumzczvkybxoxtsvbtnalgzdemikwziivujyvgithikfbccfvphjvgmcvwmtxwbtqntmtdhdlrkpwmutdbcajqceoqymmbhfqctmfcprwzislclofqooitvxlvlayuhpwabbequapcucggslyicibxhpsspqmwfkyimcyifpnztvhlhfujqxgxmaqdqezypzgdehnjwaiqwsbfxxqpvwnjydnojooyovbsepdarnspfwuftkuqihagmnxwdnwriylopqpiejylfuqbfnrpwtyjixhmkdfvdrjuhadnkdzpxrsegkudfuoorvabafyeyiaiidxsiwkgqcmwoizucnivkkzlrxrqfraqxxkhwupmzcknkmhpzrkmbjzvhslolnekkrsglhukjfawrjlsbxgejfzszmglznvmepsrxpeiwegnnthqrovavusvjagipduvtpnseracxhpmaydtmavkwphfqpqhskdnbqfhjijiraurzznnzixyyedqttxogcbhshrdpalgbizahonjxnhxrmpnimbopexjlopcpcksmmsuchfzuoyoandicgytkweyktcbwntibnedvlfrzfhctkmxqlqbhubtodxmsqwtgdzdoguqleugogdhrtkaqlugorsjjqcrvdumlrcxvydlejuyeeyurscilurxnvoizlukcyjzwpmdahbenzbfudnhaeenzvxaiunmsylrnxungvuuuvzoyowascntznuhhjtzhgqxekkmhggcbhscvocptslsfhamqvnzcgwishuapderkwvinxzgpmywtakjwajyghgyqcagfexsbscorbwjqwfjxsvvsgvyndyefbklfjfibhyukudarlkqdhlvngvajveqwqbezimcpnxchceynqqsxbpkhknsitjekmklvxomknqtpvuflkxjmnvvziqhczoonazkxnzjcpfsmzxyjwjxjgvlplutmkhblimkwlwycbspcppnoalxggkxtfqfpzgciunghjgkmzboqsbesoeawoypvqwnsfpazcijnotbnwpgotkihqiefitabsptxfvyjdhzrcahaqnqjzysqjwxtszukppjukhfnrehvfqwxdoienawyzttrtqbkfkgstlhmqoixegujweqlemjdifwdvxncjtufecrwsbtzjnkgta"

    expected = 712
    actual = difference(str1, str2)

    assert_equal expected, actual
  end
end